definitions:
  steps:
    - step: &buildDocker
        name: Building the Docker Image
        image:
          name: wfscorp.jfrog.io/docker/amazon/aws-cli:latest
          username: $JFROG_AUTOBAHN_USERNAME
          password: $JFROG_AUTOBAHN_TOKEN
          email: $JFROG_AUTOBAHN_USERNAME
        oidc: true
        script:
          - export IMAGE_TAG=${BITBUCKET_REPO_SLUG}:${BITBUCKET_BUILD_NUMBER}
          - "echo 'Building docker image ... with tag : ${IMAGE_TAG}'"
          - docker login $JFROG_URL --username $JFROG_AUTOBAHN_USERNAME --password $JFROG_AUTOBAHN_TOKEN
          - docker build -t $IMAGE_TAG .
        services:
          - docker
        caches:
          - docker

    - step: &validate-aws-policy
        name: Validating the AWS custom task role policy
        image:
          name: wfscorp.jfrog.io/docker/amazon/aws-cli:latest
          username: $JFROG_AUTOBAHN_USERNAME
          password: $JFROG_AUTOBAHN_TOKEN
          email: $JFROG_AUTOBAHN_USERNAME
        oidc: true
        script:
          - env && ls -l && aws --version
          - export AWS_REGION=$AWS_REGION
          - export AWS_ROLE_ARN=arn:aws:iam::$AWS_CLOUD_PLATFORM_PROD_ACCOUNT_ID:role/$AUTOBAHN_DEPLOYMENT_ROLE
          - export AWS_WEB_IDENTITY_TOKEN_FILE=$(pwd)/web-identity-token
          - echo $BITBUCKET_STEP_OIDC_TOKEN > $(pwd)/web-identity-token
          - |
            aws accessanalyzer validate-policy \
            --policy-type IDENTITY_POLICY \
            --policy-document file://aws-custom-task-role-policy.json \
            --region us-east-1 \
            --no-paginate \
            --no-verify-ssl

    - step: &buildAndPushToEcr
        trigger: automatic
        name: "Build and Push to ECR"
        oidc: true
        script:
          - echo "Docker setup"
          - docker login $JFROG_URL --username $JFROG_AUTOBAHN_USERNAME --password $JFROG_AUTOBAHN_TOKEN
          - echo "Building docker image ..."
          - export IMAGE_TAG=${BITBUCKET_REPO_SLUG}:${BITBUCKET_BUILD_NUMBER}
          - docker build -t $IMAGE_TAG .
          - pipe: docker://wfscorp.jfrog.io/docker/sc-provision-product-pipe:3.1.1
            variables:
              AWS_OIDC_ROLE_ARN: "arn:aws:iam::425815147557:role/$AUTOBAHN_DEPLOYMENT_ROLE"
              AWS_DEFAULT_REGION: us-east-1
              DEPLOY_ACTION: CREATE_UPDATE
              PRODUCT_NAME: "autobahn-shared-ecr-repo"
              PROVISIONING_ARTIFACT_NAME: "1"
              PROVISIONED_PRODUCT_NAME: "autobahn-shared-ecr-repo-for-$BITBUCKET_REPO_SLUG"
              PROVISIONING_PARAMETERS: >
                [{
                    "Key": "RepositoryName",
                    "Value": "$BITBUCKET_REPO_SLUG"
                    }
                ]
              TAGS: >
                [
                    { "Key": "Name","Value": "$BITBUCKET_REPO_SLUG" },
                    { "Key": "Env","Value": "prod" },
                    { "Key": "App","Value": "poseidonCdpApp" },
                    { "Key": "Owner","Value": "bi_tools@wfscorp.com" },
                    { "Key": "Domain","Value": "shared" }
                ]
          - docker login $JFROG_URL --username $JFROG_AUTOBAHN_USERNAME --password $JFROG_AUTOBAHN_TOKEN
          - pipe: docker://wfscorp.jfrog.io/docker/atlassian/aws-ecr-push-image:2.4.2
            variables:
              AWS_DEFAULT_REGION: us-east-1
              AWS_OIDC_ROLE_ARN: arn:aws:iam::425815147557:role/$AUTOBAHN_DEPLOYMENT_ROLE
              IMAGE_NAME: $BITBUCKET_REPO_SLUG
              TAGS: $BITBUCKET_BUILD_NUMBER

        services:
          - docker
        caches:
          - docker

    - step: &buildAndPushToJFrog
        trigger: automatic
        name: "Build and Push to JFrog"
        script:
          # Jfrog Configuration
          - docker login $JFROG_URL --username $JFROG_AUTOBAHN_USERNAME --password $JFROG_AUTOBAHN_TOKEN
          - pipe: docker://$JFROG_URL/$JFROG_DOCKER_REGISTRY/jfrogecosystem/jfrog-setup-cli:2.1.0
          - source ./jfrog-setup-cli.sh
          - export JFROG_CLI_BUILD_NAME=${BITBUCKET_REPO_SLUG}
          # Build/Push Image and Build Info to Jfrog
          - APP_IMAGE_URL=$JFROG_URL/$JFROG_DOCKER_REGISTRY/${BITBUCKET_REPO_SLUG}:${BITBUCKET_BUILD_NUMBER}
          - docker build -t $APP_IMAGE_URL .
          - docker push $APP_IMAGE_URL
          - echo "Collect and publish build info to JFROG"
          - jf rt dp $APP_IMAGE_URL  $JFROG_DOCKER_REGISTRY --build-name ${BITBUCKET_REPO_SLUG}  --build-number ${BITBUCKET_BUILD_NUMBER}-dkr
          - jf rt bag
          - jf rt bp ${BITBUCKET_REPO_SLUG} ${BITBUCKET_BUILD_NUMBER}-dkr
        services:
          - docker
        caches:
          - docker

    - step: &deploy
        oidc: true
        name: "Deploying ECS Fargate App"
        image:
          name: wfscorp.jfrog.io/docker/alpine
          username: $JFROG_AUTOBAHN_USERNAME
          password: $JFROG_AUTOBAHN_TOKEN
          email: $JFROG_AUTOBAHN_USERNAME
        script:
          - export APP_TAG=poseidonCdpApp
          - export AWS_REGION=us-east-1
          - docker login $JFROG_URL --username $JFROG_AUTOBAHN_USERNAME --password $JFROG_AUTOBAHN_TOKEN
          - apk add --no-cache aws-cli
          - aws --version
          - export AWS_ROLE_ARN=arn:aws:iam::425815147557:role/$AUTOBAHN_DEPLOYMENT_ROLE
          - export AWS_WEB_IDENTITY_TOKEN_FILE=$(pwd)/web-identity-token
          - echo $BITBUCKET_STEP_OIDC_TOKEN > $(pwd)/web-identity-token
          - |
            echo "Docker Image validation at ECR"
            IMAGE_URL="425815147557.dkr.ecr.us-east-1.amazonaws.com/$BITBUCKET_REPO_SLUG:$BITBUCKET_BUILD_NUMBER"
            REPO_NAME="$BITBUCKET_REPO_SLUG"
            IMAGE_TAG="$BITBUCKET_BUILD_NUMBER"
            aws ecr describe-images --repository-name $REPO_NAME --image-ids imageTag=$IMAGE_TAG --region $AWS_REGION
            if [ $? -ne 0 ]; then
              echo "Image $IMAGE_URL does not exist in ECR"
              exit 1
            else
              echo "Image $IMAGE_URL exists in ECR"
            fi
          - pipe: docker://wfscorp.jfrog.io/docker/wfs-ecs-deploy-pipe:5.1.0
            variables:
              AWS_OIDC_ROLE_ARN: "arn:aws:iam::$AWS_ACCOUNT_ID:role/$AUTOBAHN_DEPLOYMENT_ROLE"
              AWS_ECR_OIDC_ROLE_ARN: "arn:aws:iam::425815147557:role/$AUTOBAHN_DEPLOYMENT_ROLE"
              AWS_DEFAULT_REGION: "$AWS_REGION"
              PRODUCT_NAME: "autobahn-ecs-fargate-app"
              PROVISIONING_ARTIFACT_NAME: "23"
              PROVISIONED_PRODUCT_NAME: "$BITBUCKET_REPO_SLUG"
              DNS_PRODUCT_NAME: "autobahn-ecs-fargate-dns-proxy"
              DNS_PROVISIONING_ARTIFACT_NAME: "2"
              DEPLOY_ACTION: "CREATE_UPDATE"
              IMAGE_URL: "425815147557.dkr.ecr.us-east-1.amazonaws.com/$BITBUCKET_REPO_SLUG:$BITBUCKET_BUILD_NUMBER"
              NEW_RELIC_LICENSE_KEY: "$AUTOBAHN_ECS_SB_NEW_RELIC_LICENSE_KEY"
              NEW_RELIC_APP_NAME: "$BITBUCKET_PROJECT_KEY-$BITBUCKET_REPO_SLUG-$BITBUCKET_DEPLOYMENT_ENVIRONMENT"
              DXGRAPH_PIPELINES_CLIENT_ID: "$DXGRAPH_PIPELINES_CLIENT_ID"
              DXGRAPH_PIPELINES_CLIENT_SECRET: "$DXGRAPH_PIPELINES_CLIENT_SECRET"
              AUTH0_AUDIENCE: "$DX_GRAPH_AUTH0_AUDIENCE"
              AUTH0_URL: "$DX_GRAPH_AUTH0_URL"
              DX_GRAPH_URL: "$DX_GRAPH_URL"
              BITBUCKET_DEPLOYMENT_ENVIRONMENT: "$BITBUCKET_DEPLOYMENT_ENVIRONMENT"
              BITBUCKET_REPO_SLUG: "$BITBUCKET_REPO_SLUG"
              BITBUCKET_DEPLOYMENT_ENVIRONMENT_UUID: "$BITBUCKET_DEPLOYMENT_ENVIRONMENT_UUID"
              AWS_ACCOUNT_ID: "$AWS_ACCOUNT_ID"
        runs-on:
          - "workspace"
          - "linux"
          - "self.hosted"

pipelines:
  custom:
    rw-deploy-to-dev:
      - variables:
          - name: BITBUCKET_BUILD_NUMBER
      - stage:
          name: DEV Deployment Stage
          deployment: dev
          steps:
            - step:
                name: Deploy
                <<: *deploy

    rw-deploy-to-test:
      - variables:
          - name: BITBUCKET_BUILD_NUMBER
      - stage:
          name: TEST Deployment Stage
          deployment: test
          steps:
            - step:
                name: Deploy
                <<: *deploy

    rw-deploy-to-qa:
      - variables:
          - name: BITBUCKET_BUILD_NUMBER
      - stage:
          name: QA Deployment Stage
          deployment: qa
          steps:
            - step:
                name: Deploy
                <<: *deploy

    rw-deploy-to-psup:
      - variables:
          - name: BITBUCKET_BUILD_NUMBER
      - stage:
          name: PSUP Deployment Stage
          deployment: psup
          steps:
            - step:
                name: Deploy
                <<: *deploy

    rw-deploy-to-prod:
      - variables:
          - name: BITBUCKET_BUILD_NUMBER
      - stage:
          name: PROD Deployment Stage
          deployment: prod
          steps:
            - step:
                name: Deploy
                <<: *deploy

  default:
    - parallel:
        - step: *buildDocker
        - step: *validate-aws-policy
    - parallel:
        - step: *buildAndPushToJFrog
        - step: *buildAndPushToEcr
    - stage:
        name: DEV Deployment Stage
        deployment: dev
        trigger: manual
        steps:
          - step:
              name: Deploy
              <<: *deploy

branches:
  main:
    - parallel:
        - step: *buildDocker
        - step: *validate-aws-policy
    - parallel:
        - step: *buildAndPushToJFrog
        - step: *buildAndPushToEcr
    - stage:
        name: DEV Deployment Stage
        deployment: dev
        trigger: automatic
        steps:
          - step:
              name: Deploy
              <<: *deploy
    - stage:
        name: TEST Deployment Stage
        deployment: test
        trigger: manual
        steps:
          - step:
              name: Deploy
              <<: *deploy
    - stage:
        name: QA Deployment Stage
        deployment: qa
        trigger: manual
        steps:
          - step:
              name: Deploy
              <<: *deploy
    - stage:
        name: PROD Deployment Stage
        deployment: prod
        trigger: manual
        steps:
          - step:
              name: Deploy
              <<: *deploy
