// GENERATED by `npx drizzle-kit pull`. Do not hand-edit; re-pull instead.
//
// KNOWN BUG: drizzle-kit 0.31.10 renders user_profile.system_instruction's
// `''::text` default as the invalid `.default(')`. After any re-pull,
// restate it as `.default('')` by hand.
//
// Alembic remains the migration authority for this phase. Introspection is
// PARTIAL, and partial in a way that is easy to misread as complete:
// drizzle-kit 0.31.10 captured policy EXISTENCE for all 9 "_owner" policies
// below, but the `using`/`withCheck` predicate for only the 4 tables that
// carry a SINGLE policy -- conversations_owner, messages_owner,
// user_profile_owner, user_memory_owner. On the 5 tables that carry a SECOND
// policy -- tool_calls_owner, memory_outbox_owner, turn_run_owner,
// llm_calls_owner, message_feedback_owner -- the generated pgPolicy(...)
// below has NO using/withCheck at all, even though the database enforces
// `user_sub = current_setting('app.user_sub', true)` on every one of them,
// same as the four that got it right (migrations 0005:125-126, 0006:121-122,
// 0008:202-203; asserted live by backend/tests/test_rls_policies.py:556-568).
// Treat every pgPolicy(...) block below as "a policy with this name exists",
// never as "this is what it enforces."
//
// Index operator classes are ROTATED, not merely absent -- e.g.
// ix_tool_calls_turn_run_id_seq assigns int4_ops to turn_run_id (a uuid
// column) and uuid_ops to seq (an integer column); ix_conversations_user_recency
// assigns timestamptz_ops to user_sub (text) and text_ops to id (uuid). These
// are artifacts of this introspection run, not this database's real operator
// classes.
//
// Introspection also does NOT capture:
//   - FORCE ROW LEVEL SECURITY
//   - the poseidon_app and poseidon_worker roles and their grants
//     (migrations 0009 and 0010), which exist because RDS has no superuser
// Handing migration authority to Drizzle (decision Q3) requires porting
// those deliberately first. Until then, `drizzle-kit push`/`generate` must
// NOT be run against this database.
//
// The Phase 16 migration handover MUST re-derive every policy and every
// index directly from migrations 0004-0010. This file is read-only evidence
// of what one introspection run produced, never a source `drizzle-kit
// generate` reads from.

import { pgTable, varchar, index, foreignKey, unique, pgPolicy, check, uuid, text, integer, jsonb, timestamp, boolean, primaryKey } from "drizzle-orm/pg-core"
import { sql } from "drizzle-orm"



export const alembicVersion = pgTable("alembic_version", {
	versionNum: varchar("version_num", { length: 32 }).primaryKey().notNull(),
});

export const toolCalls = pgTable("tool_calls", {
	id: uuid().primaryKey().notNull(),
	turnRunId: uuid("turn_run_id").notNull(),
	userSub: text("user_sub").notNull(),
	seq: integer().notNull(),
	tool: text().notNull(),
	server: text(),
	args: jsonb(),
	resultDigest: jsonb("result_digest"),
	status: text().notNull(),
	latencyMs: integer("latency_ms"),
	error: jsonb(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("ix_tool_calls_turn_run_id_seq").using("btree", table.turnRunId.asc().nullsLast().op("int4_ops"), table.seq.asc().nullsLast().op("uuid_ops")),
	foreignKey({
			columns: [table.turnRunId],
			foreignColumns: [turnRun.id],
			name: "tool_calls_turn_run_id_fkey"
		}).onDelete("cascade"),
	unique("uq_tool_calls_turn_run_id_seq").on(table.turnRunId, table.seq),
	pgPolicy("tool_calls_admin_read", { as: "permissive", for: "select", to: ["poseidon_admin"], using: sql`true` }),
	pgPolicy("tool_calls_owner", { as: "permissive", for: "all", to: ["public"] }),
	check("ck_tool_calls_status", sql`status = ANY (ARRAY['ok'::text, 'error'::text])`),
]);

export const memoryOutbox = pgTable("memory_outbox", {
	conversationId: uuid("conversation_id").primaryKey().notNull(),
	userSub: text("user_sub").notNull(),
	lastTurnAt: timestamp("last_turn_at", { withTimezone: true, mode: 'string' }).notNull(),
	status: text().default('pending').notNull(),
	attempts: integer().default(0).notNull(),
	lastError: jsonb("last_error"),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	foreignKey({
			columns: [table.conversationId],
			foreignColumns: [conversations.id],
			name: "memory_outbox_conversation_id_fkey"
		}).onDelete("cascade"),
	pgPolicy("memory_outbox_worker", { as: "permissive", for: "all", to: ["poseidon_worker"], using: sql`true`, withCheck: sql`true`  }),
	pgPolicy("memory_outbox_owner", { as: "permissive", for: "all", to: ["public"] }),
	check("ck_memory_outbox_status", sql`status = ANY (ARRAY['pending'::text, 'done'::text, 'failed'::text])`),
]);

export const userProfile = pgTable("user_profile", {
	userSub: text("user_sub").primaryKey().notNull(),
	systemInstruction: text("system_instruction").default('').notNull(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	pgPolicy("user_profile_owner", { as: "permissive", for: "all", to: ["public"], using: sql`(user_sub = current_setting('app.user_sub'::text, true))`, withCheck: sql`(user_sub = current_setting('app.user_sub'::text, true))`  }),
]);

export const messages = pgTable("messages", {
	id: uuid().primaryKey().notNull(),
	conversationId: uuid("conversation_id").notNull(),
	userSub: text("user_sub").notNull(),
	role: text(),
	parts: jsonb().notNull(),
	turnId: uuid("turn_id"),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("ix_messages_conversation_order").using("btree", table.conversationId.asc().nullsLast().op("uuid_ops"), table.createdAt.asc().nullsLast().op("timestamptz_ops"), table.id.asc().nullsLast().op("timestamptz_ops")),
	foreignKey({
			columns: [table.conversationId],
			foreignColumns: [conversations.id],
			name: "messages_conversation_id_fkey"
		}).onDelete("cascade"),
	pgPolicy("messages_owner", { as: "permissive", for: "all", to: ["public"], using: sql`(user_sub = current_setting('app.user_sub'::text, true))`, withCheck: sql`(user_sub = current_setting('app.user_sub'::text, true))`  }),
	check("ck_messages_role", sql`role = ANY (ARRAY['user'::text, 'assistant'::text, 'system'::text])`),
]);

export const conversations = pgTable("conversations", {
	id: uuid().primaryKey().notNull(),
	userSub: text("user_sub").notNull(),
	title: text().default('New chat').notNull(),
	mode: text().default('default'),
	state: jsonb().default({}).notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	archived: boolean().default(false).notNull(),
}, (table) => [
	index("ix_conversations_user_recency").using("btree", table.userSub.asc().nullsLast().op("timestamptz_ops"), table.updatedAt.desc().nullsFirst().op("timestamptz_ops"), table.id.desc().nullsFirst().op("text_ops")),
	pgPolicy("conversations_owner", { as: "permissive", for: "all", to: ["public"], using: sql`(user_sub = current_setting('app.user_sub'::text, true))`, withCheck: sql`(user_sub = current_setting('app.user_sub'::text, true))`  }),
	check("ck_conversations_mode", sql`mode = ANY (ARRAY['existing'::text, 'prospect'::text, 'default'::text])`),
]);

export const turnRun = pgTable("turn_run", {
	id: uuid().primaryKey().notNull(),
	kind: text().default('chat_turn').notNull(),
	conversationId: uuid("conversation_id"),
	messageId: uuid("message_id"),
	userSub: text("user_sub").notNull(),
	clientTurnKey: uuid("client_turn_key"),
	turnIndex: integer("turn_index"),
	question: text(),
	mode: text(),
	parsed: jsonb().default({}).notNull(),
	answerSummary: text("answer_summary"),
	status: text().notNull(),
	inputTokens: integer("input_tokens").default(0).notNull(),
	outputTokens: integer("output_tokens").default(0).notNull(),
	latencyMs: integer("latency_ms"),
	traceId: text("trace_id"),
	error: jsonb(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	finishedAt: timestamp("finished_at", { withTimezone: true, mode: 'string' }),
	redactedAt: timestamp("redacted_at", { withTimezone: true, mode: 'string' }),
}, (table) => [
	index("ix_turn_run_conversation_id_turn_index").using("btree", table.conversationId.asc().nullsLast().op("int4_ops"), table.turnIndex.asc().nullsLast().op("uuid_ops")),
	index("ix_turn_run_created_at").using("btree", table.createdAt.asc().nullsLast().op("timestamptz_ops")),
	unique("uq_turn_run_user_sub_client_turn_key").on(table.userSub, table.clientTurnKey),
	pgPolicy("turn_run_admin_read", { as: "permissive", for: "select", to: ["poseidon_admin"], using: sql`true` }),
	pgPolicy("turn_run_owner", { as: "permissive", for: "all", to: ["public"] }),
	check("ck_turn_run_kind", sql`kind = ANY (ARRAY['chat_turn'::text, 'memory_update'::text])`),
	check("ck_turn_run_status", sql`status = ANY (ARRAY['running'::text, 'ok'::text, 'clarify'::text, 'error'::text])`),
]);

export const llmCalls = pgTable("llm_calls", {
	id: uuid().primaryKey().notNull(),
	turnRunId: uuid("turn_run_id").notNull(),
	userSub: text("user_sub").notNull(),
	seq: integer().notNull(),
	provider: text().notNull(),
	modelId: text("model_id").notNull(),
	role: text().notNull(),
	promptVersion: text("prompt_version").notNull(),
	promptHash: text("prompt_hash").notNull(),
	inputTokens: integer("input_tokens").default(0).notNull(),
	outputTokens: integer("output_tokens").default(0).notNull(),
	latencyMs: integer("latency_ms"),
	status: text().notNull(),
	error: jsonb(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("ix_llm_calls_turn_run_id_seq").using("btree", table.turnRunId.asc().nullsLast().op("int4_ops"), table.seq.asc().nullsLast().op("uuid_ops")),
	foreignKey({
			columns: [table.turnRunId],
			foreignColumns: [turnRun.id],
			name: "llm_calls_turn_run_id_fkey"
		}).onDelete("cascade"),
	unique("uq_llm_calls_turn_run_id_seq").on(table.turnRunId, table.seq),
	pgPolicy("llm_calls_admin_read", { as: "permissive", for: "select", to: ["poseidon_admin"], using: sql`true` }),
	pgPolicy("llm_calls_owner", { as: "permissive", for: "all", to: ["public"] }),
	check("ck_llm_calls_status", sql`status = ANY (ARRAY['ok'::text, 'error'::text])`),
]);

export const messageFeedback = pgTable("message_feedback", {
	id: uuid().primaryKey().notNull(),
	messageId: uuid("message_id").notNull(),
	runId: uuid("run_id").notNull(),
	userSub: text("user_sub").notNull(),
	verdict: text(),
	comment: text(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	foreignKey({
			columns: [table.messageId],
			foreignColumns: [messages.id],
			name: "message_feedback_message_id_fkey"
		}).onDelete("cascade"),
	foreignKey({
			columns: [table.runId],
			foreignColumns: [turnRun.id],
			name: "message_feedback_run_id_fkey"
		}),
	unique("uq_message_feedback_message_id_user_sub").on(table.messageId, table.userSub),
	pgPolicy("message_feedback_admin_read", { as: "permissive", for: "select", to: ["poseidon_admin"], using: sql`true` }),
	pgPolicy("message_feedback_owner", { as: "permissive", for: "all", to: ["public"] }),
	check("ck_message_feedback_verdict", sql`verdict = ANY (ARRAY['up'::text, 'down'::text])`),
]);

export const userMemory = pgTable("user_memory", {
	userSub: text("user_sub").notNull(),
	version: integer().notNull(),
	entries: jsonb().notNull(),
	createdBy: text("created_by").notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	primaryKey({ columns: [table.userSub, table.version], name: "user_memory_pkey"}),
	pgPolicy("user_memory_owner", { as: "permissive", for: "all", to: ["public"], using: sql`(user_sub = current_setting('app.user_sub'::text, true))`, withCheck: sql`(user_sub = current_setting('app.user_sub'::text, true))`  }),
	check("ck_user_memory_created_by", sql`created_by = ANY (ARRAY['user'::text, 'distiller'::text])`),
]);
